@echo off
echo Stopping any existing server on port 8000...
for /f "tokens=5" %%a in ('netstat -aon ^| findstr :8000 ^| findstr LISTENING') do taskkill /f /pid %%a 2>nul
echo Starting Bizcom AI Risk Assessment Server...
.venv\Scripts\python.exe main.py
pause
